# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class UiMainWindow(object):
    def __init__(self):
        self.horizontalLayout_10 = None
        self.btn_back = None
        self.horizontalLayout_2 = None
        self.widget = None
        self.btn_select_folder_3 = None
        self.verticalLayout_3 = None
        self.horizontalLayout_6 = None
        self.horizontalLayout_9 = None
        self.verticalLayout_4 = None
        self.le_folder_path_3 = None
        self.page_2 = None
        self.pg_up_2 = None
        self.te_code_file1 = None
        self.label_login_time_3 = None
        self.le_folder_path_2 = None
        self.home = None
        self.verticalLayout_5 = None
        self.btn_select_folder_2 = None
        self.chart_container = None
        self.verticalLayout_6 = None
        self.label_login_time_4 = None
        self.one_to_many_page = None
        self.btn_start_analysis_mode2 = None
        self.horizontalLayout_4 = None
        self.pg_down_2 = None
        self.page_3 = None
        self.table_history = None
        self.label_login_time_2 = None
        self.te_code_file2 = None
        self.groupBox_3 = None
        self.horizontalLayout_11 = None
        self.horizontalLayout_5 = None
        self.btn_start_analysis_mode1 = None
        self.horizontalLayout_3 = None
        self.le_folder_path = None
        self.verticalLayout_2 = None
        self.verticalLayout = None
        self.horizontalLayout = None
        self.each_other_page = None
        self.stackedWidget = None
        self.groupBox = None
        self.pushButton = None
        self.label_choose_folder = None
        self.btn_select_folder = None
        self.statusbar = None
        self.pushButton_2 = None
        self.horizontalLayout_7 = None
        self.horizontalLayout_8 = None
        self.groupBox_2 = None
        self.verticalLayout_7 = None
        self.page = None
        self.main_stack = None
        self.verticalLayout_8 = None
        self.centralWidget = None

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(792, 600)
        self.centralWidget = QtWidgets.QWidget(parent=main_window)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.main_stack = QtWidgets.QStackedWidget(parent=self.centralWidget)
        self.main_stack.setMidLineWidth(1)
        self.main_stack.setObjectName("main_stack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.page)
        self.stackedWidget.setObjectName("stackedWidget")
        self.each_other_page = QtWidgets.QWidget()
        self.each_other_page.setObjectName("each_other_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.each_other_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.each_other_page)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_choose_folder = QtWidgets.QLabel(parent=self.groupBox)
        self.label_choose_folder.setObjectName("label_choose_folder")
        self.horizontalLayout.addWidget(self.label_choose_folder)
        self.le_folder_path = QtWidgets.QLineEdit(parent=self.groupBox)
        self.le_folder_path.setMaxLength(1000)
        self.le_folder_path.setReadOnly(True)
        self.le_folder_path.setObjectName("le_folder_path")
        self.horizontalLayout.addWidget(self.le_folder_path)
        self.btn_select_folder = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_select_folder.setObjectName("btn_select_folder")
        self.horizontalLayout.addWidget(self.btn_select_folder)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacer_item = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacer_item)
        self.btn_start_analysis_mode1 = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_start_analysis_mode1.setObjectName("btn_start_analysis_mode1")
        self.horizontalLayout_3.addWidget(self.btn_start_analysis_mode1)
        spacer_item1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacer_item1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.each_other_page)
        self.one_to_many_page = QtWidgets.QWidget()
        self.one_to_many_page.setObjectName("one_to_many_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.one_to_many_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.one_to_many_page)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_login_time_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_login_time_3.setObjectName("label_login_time_3")
        self.horizontalLayout_9.addWidget(self.label_login_time_3)
        self.le_folder_path_2 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.le_folder_path_2.setMaxLength(1000)
        self.le_folder_path_2.setReadOnly(True)
        self.le_folder_path_2.setObjectName("le_folder_path_2")
        self.horizontalLayout_9.addWidget(self.le_folder_path_2)
        self.btn_select_folder_2 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.btn_select_folder_2.setObjectName("btn_select_folder_2")
        self.horizontalLayout_9.addWidget(self.btn_select_folder_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_login_time_4 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_login_time_4.setObjectName("label_login_time_4")
        self.horizontalLayout_11.addWidget(self.label_login_time_4)
        self.le_folder_path_3 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.le_folder_path_3.setMaxLength(1000)
        self.le_folder_path_3.setReadOnly(True)
        self.le_folder_path_3.setObjectName("le_folder_path_3")
        self.horizontalLayout_11.addWidget(self.le_folder_path_3)
        self.btn_select_folder_3 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.btn_select_folder_3.setObjectName("btn_select_folder_3")
        self.horizontalLayout_11.addWidget(self.btn_select_folder_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacer_item2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacer_item2)
        self.btn_start_analysis_mode2 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.btn_start_analysis_mode2.setObjectName("btn_start_analysis_mode2")
        self.horizontalLayout_10.addWidget(self.btn_start_analysis_mode2)
        spacer_item3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacer_item3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.one_to_many_page)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.table_history = QtWidgets.QTableWidget(parent=self.page)
        self.table_history.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table_history.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table_history.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_history.setShowGrid(False)
        self.table_history.setObjectName("table_history")
        self.table_history.setColumnCount(0)
        self.table_history.setRowCount(0)
        self.table_history.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.table_history)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacer_item4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacer_item4)
        self.pg_up_2 = QtWidgets.QPushButton(parent=self.page)
        self.pg_up_2.setObjectName("pg_up_2")
        self.horizontalLayout_5.addWidget(self.pg_up_2)
        spacer_item5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacer_item5)
        self.pg_down_2 = QtWidgets.QPushButton(parent=self.page)
        self.pg_down_2.setObjectName("pg_down_2")
        self.horizontalLayout_5.addWidget(self.pg_down_2)
        spacer_item6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacer_item6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.label_login_time_2 = QtWidgets.QLabel(parent=self.page)
        self.label_login_time_2.setMidLineWidth(1)
        self.label_login_time_2.setObjectName("label_login_time_2")
        self.verticalLayout_7.addWidget(self.label_login_time_2)
        self.main_stack.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.home = QtWidgets.QPushButton(parent=self.page_3)
        self.home.setObjectName("home")
        self.horizontalLayout_6.addWidget(self.home)
        spacer_item7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacer_item7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.chart_container = QtWidgets.QWidget(parent=self.page_3)
        self.chart_container.setObjectName("chart_container")
        self.verticalLayout_5.addWidget(self.chart_container)
        self.widget = QtWidgets.QWidget(parent=self.page_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_5.addWidget(self.widget)
        self.main_stack.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacer_item8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacer_item8)
        self.btn_back = QtWidgets.QPushButton(parent=self.page_2)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        spacer_item9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacer_item9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.te_code_file2 = QtWidgets.QTextEdit(parent=self.page_2)
        self.te_code_file2.setReadOnly(True)
        self.te_code_file2.setObjectName("te_code_file2")
        self.horizontalLayout_4.addWidget(self.te_code_file2)
        self.te_code_file1 = QtWidgets.QTextEdit(parent=self.page_2)
        self.te_code_file1.setReadOnly(True)
        self.te_code_file1.setObjectName("te_code_file1")
        self.horizontalLayout_4.addWidget(self.te_code_file1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.main_stack.addWidget(self.page_2)
        self.verticalLayout_8.addWidget(self.main_stack)
        main_window.setCentralWidget(self.centralWidget)
        self.statusbar = QtWidgets.QStatusBar(parent=main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslate_ui(main_window)
        self.main_stack.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "Python 代码查重工具"))
        self.groupBox_2.setTitle(_translate("MainWindow", "选择查重模式"))
        self.pushButton_2.setText(_translate("MainWindow", "一对多"))
        self.pushButton.setText(_translate("MainWindow", "文件夹内互查"))
        self.groupBox.setTitle(_translate("MainWindow", "开始一个新的查重任务"))
        self.label_choose_folder.setText(_translate("MainWindow", "代码文件夹路径："))
        self.btn_select_folder.setText(_translate("MainWindow", "选择文件夹"))
        self.btn_start_analysis_mode1.setText(_translate("MainWindow", "开始分析"))
        self.groupBox_3.setTitle(_translate("MainWindow", "开始一个新的查重任务"))
        self.label_login_time_3.setText(_translate("MainWindow", "被测代码文件"))
        self.btn_select_folder_2.setText(_translate("MainWindow", "选择文件"))
        self.label_login_time_4.setText(_translate("MainWindow", "代码文件夹路径："))
        self.btn_select_folder_3.setText(_translate("MainWindow", "选择文件夹"))
        self.btn_start_analysis_mode2.setText(_translate("MainWindow", "开始分析"))
        self.pg_up_2.setText(_translate("MainWindow", "上一页"))
        self.pg_down_2.setText(_translate("MainWindow", "下一页"))
        self.label_login_time_2.setText(_translate("MainWindow", "登录时间："))
        self.home.setText(_translate("MainWindow", "返回主页"))
        self.btn_back.setText(_translate("MainWindow", "返回结果列表"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
